@echo off
setlocal enabledelayedexpansion
set "fileRead=refman.tex"
set "fileWrite=generated_content.tex"
set "mainFile=report.tex"
set "bulidFile=make.bat"
set "searchStart=%--- Begin generated contents ---"
set "searchEnd=%--- End generated contents ---"
set "header_line="
set "end_line="

IF EXIST %fileRead% (
    ECHO File %fileRead% exists.
    IF EXIST %fileWrite% (
        ECHO File %fileWrite% exists.
        IF EXIST %mainFile% (
            ECHO File %mainFile% exists.            
            IF EXIST %bulidFile% (
                ECHO File %bulidFile% exists.            
                GOTO ExecuteCopy
            ) ELSE (
                ECHO File %bulidFile% does not exist.
                GOTO EndOfProgram
            )
        ) ELSE (
            ECHO File %mainFile% does not exist.
            GOTO EndOfProgram
        )
    ) ELSE (
        ECHO File %fileWrite% does not exist.
        GOTO EndOfProgram
    )
) ELSE (
    ECHO File %fileRead% does not exist.
    GOTO EndOfProgram
)

:ExecuteCopy
for /f "tokens=1  delims=[]" %%a in ('find /i /n "%searchStart%" "%fileRead%" ') do set "header_line=%%a"
for /f "tokens=1  delims=[]" %%a in ('find /i /n "%searchEnd%" "%fileRead%" ') do set "end_line=%%a"

set counter=2
set /a end_line=!end_line!-%counter%

if /i %header_line% GEQ %end_line% (
    ECHO %fileRead% in not generated by Doxygen.
    GOTO build
)

<nul set /p x=>"%fileWrite%"
for /f "usebackq tokens=*" %%A IN ("%fileRead%") DO (
    set /a counter=!counter!+1
    if !counter! GEQ %header_line% (
        if !counter! LEQ %end_line% (
            ECHO %%A>>"%fileWrite%"
        )
    )
)

ECHO All strings copied form %fileRead% to %fileWrite%.
del /f %fileRead%
ECHO  %fileRead% has been deleted.
copy %mainFile% %fileRead%
ECHO  %mainFile% has been renamed to %fileRead%.

:build
ECHO  run script %bulidFile%.
%bulidFile%

:EndOfProgram
pause>nul